opcodes:
  - name: ADD
    bit_ranges:
      - start: 0
        end: 6
        value: 51
      - start: 5  # Overlapping bit range
        end: 11
        value: 0
    arguments:
      - name: rd
      - name: rs1
      - name: rs3  # Invalid argument
  - name: SUB
    bit_ranges:
      - start: 0
        end: 6
        value: 51
      - start: 7
        end: 11
        value: 128  # Value exceeds bit width
    arguments:
      - name: rd
      - name: rs1
      # Missing 'rs2'
  - name: MUL
    bit_ranges:
      - start: 0
        end: 6
        value: 51
      - start: 12
        end: 14
        value: 0
    arguments:
      - name: rd
      - name: rs1
      - name: rs2
